#ifndef OPERATIONSONMATRICES_CONSTANTS_H
#define OPERATIONSONMATRICES_CONSTANTS_H
#define W 119
#define S 115
#define FIRST_BYTE_ARROW 224
#define ARROW_UP 72
#define ARROW_DOWN 80
#define ESC 27
#define ENTER 13
#define ZERO 48
#define ONE 49
#define TWO 50
#define THREE 51
#define FOUR 52
#define FIVE 53
#define SIX 54
#define SEVEN 55
#define EIGHT 56
#define NINE 57
#define MINMAX_RANDOMIZE_INTERVAL 10
#define MIN_MATRIX_SIZE 1
#define MAX_MATRIX_SIZE 8
#define MIN_ARROW_POSITION 1
#define MAX_ARROW_POSITION 10
#endif //OPERATIONSONMATRICES_CONSTANTS_H
