
#ifndef HIERARCHICALSTRUCTUREOFDATASTORAGE_CONSTANTS_H
#define HIERARCHICALSTRUCTUREOFDATASTORAGE_CONSTANTS_H
#define W 119
#define S 115
#define FIRST_BYTE_ARROW 224
#define ARROW_UP 72
#define ARROW_DOWN 80
#define ESC 27
#define ENTER 13
#define ZERO 48
#define ONE 49
#define TWO 50
#define THREE 51
#define FOUR 52
#define FIVE 53
#define SIX 54
#define SEVEN 55
#define EIGHT 56
#define NINE 57
#define MIN_ARROW_POSITION 1
#define MAX_ARROW_POSITION_UNI 7
#define MAX_ARROW_POSITION 8
#define SPLIT_USUAL_VALUE 1
#define IDENTITY_UNIVERSITY 85
#define IDENTITY_FACULTY 70
#define IDENTITY_DEPARTMENT 68
#define IDENTITY_GROUP 71
#define IDENTITY_STUDENT 83
#endif //HIERARCHICALSTRUCTUREOFDATASTORAGE_CONSTANTS_H
